version: '3.7'

services:

  frontend:
    container_name: Smakert-events
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true